try {
    console.log(hello);   
}
catch (error){
    console.log("naah");
}
finally {
    console.log("worked");
    
}